import { Provider } from "./types";

// Built-in data describes sites only. Model facts come from the shared model
// directory and the rebuildable models-cache.json, never from presets.
export const PRESET_PROVIDERS: Omit<Provider, 'vaultKey'>[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com",
    authMode: "api_key",
    models: [],
  },
  {
    id: "anthropic-agent",
    name: "Claude 订阅 (Pro/Max)",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com",
    authMode: "oauth",
    executionMode: "agent_native",
    nativeAgentIds: ["claude"],
    models: [],
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "openai-codex",
    name: "ChatGPT",
    type: "openai",
    baseUrl: "https://chatgpt.com/backend-api/codex",
    authMode: "oauth",
    executionMode: "agent_native",
    nativeAgentIds: ["codex"],
    models: [],
  },
  {
    id: "volcengine",
    name: "火山引擎",
    type: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    endpoints: [
      { type: "openai", baseUrl: "https://ark.cn-beijing.volces.com/api/v3" },
      { type: "anthropic", baseUrl: "https://ark.cn-beijing.volces.com/api/v3" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "zai",
    name: "智谱 AI（国内站）",
    type: "openai",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    endpoints: [
      { type: "openai", baseUrl: "https://open.bigmodel.cn/api/paas/v4" },
      { type: "anthropic", baseUrl: "https://open.bigmodel.cn/api/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "zai-global",
    name: "Z.AI（国际站）",
    type: "openai",
    baseUrl: "https://api.z.ai/api/paas/v4",
    endpoints: [
      { type: "openai", baseUrl: "https://api.z.ai/api/paas/v4" },
      { type: "anthropic", baseUrl: "https://api.z.ai/api/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "zai-global-coding",
    name: "Z.AI Coding Plan",
    type: "openai",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://api.z.ai/api/coding/paas/v4", plan: "coding" },
      { type: "anthropic", baseUrl: "https://api.z.ai/api/anthropic", plan: "coding" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "minimax",
    name: "MiniMax（国内站）",
    type: "openai",
    baseUrl: "https://api.minimaxi.com/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://api.minimaxi.com/v1" },
      { type: "anthropic", baseUrl: "https://api.minimaxi.com/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "minimax-global",
    name: "MiniMax（国际站）",
    type: "openai",
    baseUrl: "https://api.minimax.io/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://api.minimax.io/v1" },
      { type: "anthropic", baseUrl: "https://api.minimax.io/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "minimax-global-coding",
    name: "MiniMax Token Plan（国际）",
    type: "openai",
    baseUrl: "https://api.minimax.io/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://api.minimax.io/v1", plan: "token" },
      { type: "anthropic", baseUrl: "https://api.minimax.io/anthropic", plan: "token" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    type: "openai",
    baseUrl: "https://api.deepseek.com",
    endpoints: [
      { type: "openai", baseUrl: "https://api.deepseek.com" },
      { type: "anthropic", baseUrl: "https://api.deepseek.com/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "moonshot",
    name: "Moonshot",
    type: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://api.moonshot.ai/v1" },
      { type: "anthropic", baseUrl: "https://api.moonshot.ai/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "kimi-coding",
    // Keep this ID for existing configurations while presenting it as Kimi.
    name: "Kimi（国内站）",
    type: "openai",
    baseUrl: "https://api.moonshot.cn/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://api.moonshot.cn/v1" },
      { type: "anthropic", baseUrl: "https://api.moonshot.cn/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "kimi-coding-plan",
    name: "Kimi Coding Plan",
    type: "openai",
    baseUrl: "https://api.kimi.com/coding/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://api.kimi.com/coding/v1", plan: "coding" },
      { type: "anthropic", baseUrl: "https://api.kimi.com/coding", plan: "coding" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "qwen",
    name: "阿里云百炼",
    type: "openai",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
      { type: "anthropic", baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "qwen-coding",
    name: "阿里云百炼 Coding Plan",
    type: "openai",
    baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://coding.dashscope.aliyuncs.com/v1", plan: "coding" },
      { type: "anthropic", baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic", plan: "coding" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "qwen-token-plan",
    name: "阿里云百炼 Token Plan",
    type: "openai",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1", plan: "token" },
      { type: "anthropic", baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic", plan: "token" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "qianfan",
    name: "百度千帆",
    type: "openai",
    baseUrl: "https://qianfan.baidubce.com/v2",
    endpoints: [
      { type: "openai", baseUrl: "https://qianfan.baidubce.com/v2" },
      { type: "anthropic", baseUrl: "https://qianfan.baidubce.com/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "qianfan-coding",
    name: "百度千帆 Token Plan",
    type: "openai",
    baseUrl: "https://qianfan.baidubce.com/v2/tokenplan/personal",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://qianfan.baidubce.com/v2/tokenplan/personal", plan: "token" },
      { type: "anthropic", baseUrl: "https://qianfan.baidubce.com/anthropic/tokenplan/personal", plan: "token" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "glm-coding",
    name: "GLM Coding Plan",
    type: "openai",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4", plan: "coding" },
      { type: "anthropic", baseUrl: "https://open.bigmodel.cn/api/anthropic", plan: "coding" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "minimax-coding",
    name: "MiniMax Token Plan",
    type: "openai",
    baseUrl: "https://api.minimaxi.com/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://api.minimaxi.com/v1", plan: "token" },
      { type: "anthropic", baseUrl: "https://api.minimaxi.com/anthropic", plan: "token" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "volcengine-coding",
    name: "火山引擎 Coding Plan",
    type: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3", plan: "coding" },
      { type: "anthropic", baseUrl: "https://ark.cn-beijing.volces.com/api/coding", plan: "coding" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "volcengine-agent",
    name: "火山引擎 Agent Plan",
    type: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3", plan: "agent" },
      { type: "anthropic", baseUrl: "https://ark.cn-beijing.volces.com/api/plan", plan: "agent" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "tencent",
    name: "腾讯云",
    type: "openai",
    baseUrl: "https://tokenhub.tencentmaas.com/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://tokenhub.tencentmaas.com/v1" },
      { type: "anthropic", baseUrl: "https://tokenhub.tencentmaas.com" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "tencent-token-plan",
    name: "腾讯云 Token Plan",
    type: "openai",
    baseUrl: "https://api.lkeap.cloud.tencent.com/plan/v3",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://api.lkeap.cloud.tencent.com/plan/v3", plan: "token" },
      { type: "anthropic", baseUrl: "https://api.lkeap.cloud.tencent.com/plan/anthropic", plan: "token" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "siliconflow",
    name: "硅基流动",
    type: "openai",
    baseUrl: "https://api.siliconflow.cn/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://api.siliconflow.cn/v1" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    type: "openai",
    baseUrl: "https://api.x.ai/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "xai-grok-build",
    name: "SuperGrok",
    type: "openai",
    baseUrl: "https://grok.com",
    authMode: "oauth",
    executionMode: "agent_native",
    nativeAgentIds: [],
    cliOnly: true,
    models: [],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    type: "openai",
    baseUrl: "https://github.com/features/copilot",
    authMode: "oauth",
    executionMode: "agent_native",
    nativeAgentIds: [],
    cliOnly: true,
    models: [],
  },
  {
    id: "mistral",
    name: "Mistral",
    type: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "stepfun",
    name: "阶跃星辰",
    type: "openai",
    baseUrl: "https://api.stepfun.com/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "stepfun-global",
    name: "StepFun (Global)",
    type: "openai",
    baseUrl: "https://api.stepfun.ai/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "xiaomi",
    name: "小米 MiMo",
    type: "openai",
    baseUrl: "https://api.xiaomimimo.com/v1",
    endpoints: [
      { type: "openai", baseUrl: "https://api.xiaomimimo.com/v1" },
      { type: "anthropic", baseUrl: "https://api.xiaomimimo.com/anthropic" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "xiaomi-coding",
    name: "小米 MiMo Token Plan",
    type: "openai",
    baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1", plan: "token" },
      { type: "anthropic", baseUrl: "https://token-plan-sgp.xiaomimimo.com/anthropic", plan: "token" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    authMode: "api_key",
    models: [],
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    modelCatalogId: "opencode-go",
    type: "openai",
    baseUrl: "https://opencode.ai/zen/go/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://opencode.ai/zen/go/v1", plan: "coding" },
      { type: "openai", protocol: "responses", baseUrl: "https://opencode.ai/zen/go/v1", plan: "coding" },
      { type: "anthropic", baseUrl: "https://opencode.ai/zen/go", plan: "coding" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen",
    modelCatalogId: "opencode",
    type: "openai",
    baseUrl: "https://opencode.ai/zen/v1",
    endpoints: [
      { type: "openai", protocol: "chat", baseUrl: "https://opencode.ai/zen/v1" },
      // The gateway speaks BOTH protocols on this host — the anthropic
      // handler appends /v1/messages and /v1/models itself, so the endpoint
      // base carries NO /v1 (with /v1 it would double up: /zen/v1/v1/models).
      // Live-verified 2026-08-22: x-api-key "public" + x-preview-f-free on
      // /v1/messages returns a proper Anthropic-format reply, so Claude Code
      // can use the free tier through this endpoint. NOTE the gateway only
      // translates ARRAY-form content blocks — plain string content reaches
      // upstream empty (harmless: the Anthropic SDK Claude Code uses always
      // sends array form).
      { type: "anthropic", baseUrl: "https://opencode.ai/zen" },
    ],
    authMode: "api_key",
    models: [],
  },
  {
    id: "ollama",
    name: "Ollama (本地)",
    type: "openai",
    baseUrl: "http://127.0.0.1:11434/v1",
    authMode: "none",
    models: [],
  },
  {
    id: "litellm",
    name: "LiteLLM (本地)",
    type: "openai",
    baseUrl: "http://localhost:4000",
    authMode: "none",
    models: [],
  },
];
